Adding checks
TheTrioWLT/sacc pull request #2
Opened 2022-01-19 20:56 UTC by HernanW4

2022-01-19 21:38 UTC, TroyNeubauer requested changes

2022-01-19 21:38 UTC, TroyNeubauer commented on .github/workflows/main.yml
> +        sudo apt-get install -y libxcb-xfixes0-dev libxcb-shape0-dev
We only needed these libs for flight tracking, so they can be deleted for this

2022-01-27 21:04 UTC, TroyNeubauer commented
ping

2022-01-27 21:05 UTC, TroyNeubauer approved these changes
Looks good! We might want to get rid of the cargo run because in the future it will probably fail because of no input files, but that is a change for another day

2022-01-28 16:18 UTC, newcomb-luke commented
I'd suggest, because we won't even be able to do cargo run until we can test the program by having it run on source files, we remove cargo run from the CargoBuild checks so that the checks can pass.
Alternatively we can just merge this and when we merge in the command_line branch it will be fixed

2022-01-31 04:44 UTC, TroyNeubauer approved these changes

2022-01-31 21:10 UTC, merged